import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import pages from "@/content/pages.json";

// Page markup is generated by scripts/extract-site.mjs from the site mirror.
const CONTENT_DIR = path.join(process.cwd(), "src/content");

export function getAllPages() {
  return pages;
}

export function getPageByRoute(route) {
  return pages.find((p) => p.route === route) ?? null;
}

export async function getPageHtml(slug) {
  return fs.readFile(path.join(CONTENT_DIR, "pages", `${slug}.html`), "utf8");
}

export async function getPartialHtml(name) {
  return fs.readFile(path.join(CONTENT_DIR, "partials", `${name}.html`), "utf8");
}
